version: '3'

services:
  fief_client:
      build: 
        context: ./
        dockerfile: Dockerfile
      command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
      environment: 
        PYTHONUNBUFFERED: 1
        SECRET_KEY: "7ed60dd91c5ea97f310650a7598201109cf4e587e826d112e93d3f746ba7fd97"
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ports:
        - 8081:8081
      volumes:
        - ./:/app